"""Sprint 5 resource-adaptive ignore constants."""

BENCHMARK_NOISE_FLOOR = 0.06
MAX_PRESSURE_THRESHOLD = 0.50
BUDGET_RATIOS = (1.00, 0.75, 0.50, 0.25, 0.00)
BYTES_PER_VALUE = 8

RESOURCE_STRESS_SEEDS = (211, 223, 227, 229, 233)
RESOURCE_STRESS_LENGTH = 600
RESOURCE_STRESS_LAG_WINDOW = 5
RESOURCE_STRESS_TRAIN_LABEL_ROWS = range(5, 420)
RESOURCE_STRESS_TEST_LABEL_ROWS = range(510, 600)

RESOURCE_STRESS_TARGET = "target"
RESOURCE_STRESS_STRONG_SOURCES = ("strong_1", "strong_2", "strong_3")
RESOURCE_STRESS_MEDIUM_SOURCES = ("medium_1", "medium_2", "medium_3", "medium_4")
RESOURCE_STRESS_WEAK_SOURCES = ("weak_1", "weak_2", "weak_3", "weak_4")
RESOURCE_STRESS_NOISE_SOURCES = ("noise_1", "noise_2", "noise_3", "noise_4")
RESOURCE_STRESS_SOURCES = (
    RESOURCE_STRESS_STRONG_SOURCES
    + RESOURCE_STRESS_MEDIUM_SOURCES
    + RESOURCE_STRESS_WEAK_SOURCES
    + RESOURCE_STRESS_NOISE_SOURCES
)
RESOURCE_STRESS_COLUMNS = (RESOURCE_STRESS_TARGET,) + RESOURCE_STRESS_SOURCES
RESOURCE_STRESS_CSV_COLUMNS = ("step",) + RESOURCE_STRESS_COLUMNS
